spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
    url: jdbc:mariadb://localhost:3306/spring_basic
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ENC(oJMU8tRiFplaGm/Kv5nAdsmqWwIpS6m7)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
  sql:
    init:
      mode: always
jasypt:
  encryptor:
    password: sddc
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator